### ISSUE TITLE
Check actually prevents from rebasing sometimes

### ISSUE THREAD

**Issue by rpitonak** [packit/pre-commit-hooks#2]
I did some changes locally and `git add` the changed files. I wanted to do a commit but `pre-commit` yield that I have to rebase. 

But running `git pull --rebase upstream master` outputs:
```
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
```

So, I should commit the changes to rebase but I have to rebase to commit the changes? 
![Alt Text](https://media.giphy.com/media/9UqRcQHzBou6A/giphy.gif)

**Comment by lachmanfrantisek** [comment]
Maybe this could help: https://git-scm.com/book/en/v1/Git-Tools-Stashing

**Comment by lachmanfrantisek** [comment]
Or skip the check:

```sh
env SKIP=check-rebase git commit
```

**Comment by lachmanfrantisek** [comment]
We need to print that advice. What is the prefered way?
- use the env-var
- commit with `-n`
- stash

**Comment by rpitonak** [comment]
I think it is best to use `stash` because using env var user can avoid to actually rebase after.

**Comment by TomasTomecek** [comment]
I'd print all of them - so that people can pick the preferred solution (all of them at once: stash && commit -n with the the env var, force push and run)

**Comment by csomh** [comment]
We decided to close this in favour of other work. If you still think it's important, please re-open it.
