### ISSUE TITLE
pre-commit 3.0 dropped `sha` for revisions

### ISSUE THREAD

**Issue by r0x0d** [packit/pre-commit-hooks#31]
pre-commit dropped the possibility to have `sha` as a revision in a hook: https://github.com/pre-commit/pre-commit/releases/tag/v3.0.0

Probably it would be nice to create a tag at some point to prevent errors in other configs.

**Comment by jpopelka** [comment]
One can change the `sha` to `rev` (manually or with `pre-commit migrate-config`) to fix it but we can add a tag (anyone against 1.0.0?), indeed.

**Comment by r0x0d** [comment]
I may have posted this here before reading the full changelog, ⁣ but yes, `sha` will become `rev` in 3.0. But also, I remember seeing somewhere that pre-commit recommends having tags instead of hashes for rev too.

**Comment by jpopelka** [comment]
Just created [v1.0.0](https://github.com/packit/pre-commit-hooks/releases/tag/v1.0.0)
